version: "3"

#extra_hosts:
#  - "host.docker.internal:172.17.0.1"

services:

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus
    ports:
      - "80:9090"

  json-exporter:
    image: prometheuscommunity/json-exporter:v0.6.0
    container_name: json-exporter
    volumes:
      - ./json-exporter/config.yml:/config.yml
    ports:
      - "7979:7979"

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/data
    ports:
      - "9093:9093"

  grafana:
    image: grafana/grafana-oss:9.5.1
    container_name: grafana
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    volumes:
      - ./grafana/custom.ini:/etc/grafana/custom.ini
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
  
  jaeger:
    image: jaegertracing/all-in-one:1.45
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "8081:16686"
      - "14250:14250"
      - "4317:4317"
   
  jenkins:
    image: jenkins/jenkins:2.414-jdk11
    container_name: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
    ports:
      - "8080:8080"
       
      
networks:
  default:
    driver: bridge

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
  jenkins_data: