# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alerting specifies settings related to the Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alertmanager's default port is 9093
          - 10.123.1.44:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - rules.yml
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['10.120.1.242:8085']
        labels:
          application: 'app ST queries'

  - job_name: 'Jenkins QA'
    #scheme: https
    metrics_path: '/prometheus'
    scrape_interval: 15s
    static_configs:
     - targets: ['10.123.1.30:8080']
       labels:
         application: 'jenkins data'

  - job_name: 'Jenkins QA - Metrics plugin'
    #scheme: https
    metrics_path: '/probe'
    params:
      module: [default]
    scrape_interval: 15s
    static_configs:
     - targets: 
       - http://10.123.1.30:8080/metrics/Thni4u2v3kBLuGNbsXUcg9um2p8UWvHwmZHJbdX__k7QninbXOoVZIO95KFqZykV/healthcheck
       labels:
         application: 'jenkins data'
    relabel_configs:
     - source_labels: [__address__]
       target_label: __param_target
     - source_labels: [__param_target]
       target_label: instance
     - target_label: __address__
       replacement: 10.123.1.44:7979
