{
 "title": "Jenkins QA - Estat dels Jobs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top10 Jobs Lents",
   "type": "gauge",
   "description": "Top10 Jobs que tenen el temps d'execució més alt",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,default_jenkins_builds_duration_milliseconds_summary_sum/default_jenkins_builds_duration_milliseconds_summary_count)",
     "legendFormat": "{{jenkins_job}}{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Top10 Jobs Rapids",
   "type": "gauge",
   "description": "Top10 Jobs que tenen el temps d'execució més baix",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(10,default_jenkins_builds_duration_milliseconds_summary_sum/default_jenkins_builds_duration_milliseconds_summary_count)",
     "legendFormat": "{{jenkins_job}}"
    }
   ]
  },
  {
   "title": "Top10 Jobs Fallits sobre el total (low is worst)",
   "type": "table",
   "description": "Top10 Jobs per menys execucions finalitzades sobre el total.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "bottomk(10,\r\ndefault_jenkins_builds_success_build_count_total{jenkins_job=~\".*\"}\r\n  / \r\ndefault_jenkins_builds_duration_milliseconds_summary_count{jenkins_job=~\".*\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top10 Jobs Fallits",
   "type": "table",
   "description": "Top10 Jobs amb resultat final d'execució fallida",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "topk(10,default_jenkins_builds_failed_build_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Etapes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Etapes - Duració mitja",
   "type": "stat",
   "description": "Mostra la duració mitja (sum de duracio d'execucions/nombre total d'execucions)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(default_jenkins_builds_last_stage_duration_milliseconds_summary_sum) by (stage) \r\n/\r\nsum(default_jenkins_builds_last_stage_duration_milliseconds_summary_count) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Top20 - Etapes per job més costoses en temps",
   "type": "stat",
   "description": "Mostra el top20 de les etapes per job que més costoses han estat en temps",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(default_jenkins_builds_last_stage_duration_milliseconds_summary_sum) by (jenkins_job,stage)\r\n/\r\nsum(default_jenkins_builds_last_stage_duration_milliseconds_summary_count) by (jenkins_job,stage))",
     "legendFormat": "{{stage}} {{jenkins_job}}"
    }
   ]
  }
 ]
}